### ISSUE TITLE
Not able to see the user bio in profile Page

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#23]
User bio is not able to render in the user profile

**Comment by MuhammedJaseemVK** [comment]
@Shu12388y Please assign this issue to me.  I would love to work on this

**Comment by Shu12388y** [comment]
@MuhammedJaseemVK Start working on the issue

**Comment by MuhammedJaseemVK** [comment]
@Shu12388y Hi. Can you help me. I am getting this error while login in. 
`Login error: Error: secretOrPrivateKey must have a value
    at module.exports.[project]/node_modules/jsonwebtoken/sign.js [app-route] (ecmascript).module.exports [as sign] (/home/jaseem/open source/scamwebsiteV1/.next/server/chunks/node_modules_ed306f._.js:14547:24)
    at POST (/home/jaseem/open source/scamwebsiteV1/.next/server/chunks/src_ffd4ac._.js:120:176)
    at async /home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55778
    at async eO.execute (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46527)
    at async eO.handle (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57112)
    at async doRender (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:1352:42)
    at async cacheEntry.responseCache.get.routeKind (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:1574:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:1482:28)
    at async DevServer.renderPageComponent (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:1908:24)
    at async DevServer.renderToResponseImpl (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:1946:32)
    at async DevServer.pipeImpl (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:921:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/base-server.js:817:17)
    at async /home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/home/jaseem/open source/scamwebsiteV1/node_modules/next/dist/server/lib/start-server.js:141:13)`
    
  I have created a .env.local file in root folder. I get MONGO_URI but not SECRET_KEY. Please provide assistance

**Comment by Shu12388y** [comment]
Add the Secret key

**Comment by MuhammedJaseemVK** [comment]
@Shu12388y I have added it. But still not picking the key

**Comment by Shu12388y** [comment]
@MuhammedJaseemVK have you pull the latest code
